#!/bin/sh
#
# file: /etc/ppp/yaca-chat-script
# Yaca chat script for pppd
#

exec chat -v\
     TIMEOUT 120\
     ATZ OK\
     TIMEOUT 5\
     AT OK\
     ATE0V1\&C1\&D2 OK\
     ATS7=120 OK\
     ATZ OK\
     AT OK\
     ATE0V1\&C1\&D2 OK\
     ATS7=120 OK\
     ATX3 OK\
     ATDT1234 'CONNECT 9600'
